### ISSUE TITLE
2차 신청서 만들기 - Payment 옵션, 숙박 옵션 받기

### ISSUE THREAD

**Issue by zoonoo** [icists/ams#31]

**Comment by zoonoo** [comment]
모델에 송금인 명(remitter_name) 추가해야할듯. 
슬랙에 올라가있는 워드 파일 바탕으로 제작. 
모든 금액을 USD, KRW 구분해서 하면 좋을듯.

**Comment by zoonoo** [comment]
Accommodation 신청을 우선 받고, 추후에 우리가 배정을 해줘야 하니, 
Participant 모델에 accommodation_select 같은거 추가해주면 되지 않을까요

**Comment by Shavakan** [comment]
![2015-06-02 10 17 46](https://cloud.githubusercontent.com/assets/4944891/7936593/442cee72-0975-11e5-83f4-649e2f33d655.png)

**Comment by zoonoo** [comment]
![5](https://cloud.githubusercontent.com/assets/5508584/7936874/5f67f324-0977-11e5-92eb-f7da904bf6f8.JPG)
